### ISSUE TITLE
"undefined - Cannot read properties of undefined (reading 'HREF')"

### ISSUE THREAD

**Issue by glowinthedarkninja** [bambanah/deemix#129]
Installed to MacOS 15.1 with M1 processor.
Deezer ARL is active and logged in.
Drive I store everything to is mounted.
FLAC quality files has been selected for download.
Any ideas or leads to help me fix this?
I'm so unbelievably frustrated with this error, and unfortunately too uneducated to fix it myself. I tried to fix it myself with ChatGPT for like a month with no success.

**Comment by bambanah** [comment]
Hi there! What version of deemix do you have installed? I'm unable to recreate this bug on the latest gui version [0.3.2](https://github.com/bambanah/deemix/releases/tag/deemix-gui%400.3.2)

**Comment by glowinthedarkninja** [comment]
I don't know what witchcraft magic you weaved in computer rune speak, but 0.3.2 fixed my problem. Thank you so much!

**Comment by sirynka** [comment]
Do i have the same problem?
Getting an error when trying to download list of liked songs.

P. S. I've successfully downloaded couple of albums but it doesn't work for "Liked". 

```
win32 - Windows_NT 10.0.26100 x64

2025-09-18T14:05:01.715Z [info] Listening on 127.0.0.1:6595
2025-09-18T14:05:11.677Z [info] Currently running deemix-gui version 2022.12.14-r222.5d447b6035
2025-09-18T14:05:11.677Z [info] deemix-lib version 3.6.14

...

2025-09-18T14:12:51.721Z [info] [album_13717022_3] Completed download of 14 - I Started a Joke (feat. Becky Hanson).mp3
2025-09-18T14:12:51.986Z [info] [album_13717022_3] Finished downloading
2025-09-18T14:12:51.987Z [info] 
2025-09-18T14:13:25.066Z [info] Adding https://deezer.com/playlist/6742402844 to queue
2025-09-18T14:13:28.949Z [error] Cannot read properties of undefined (reading 'HREF')
TypeError: Cannot read properties of undefined (reading 'HREF')
    at map_track (C:\Users\sirynka\AppData\Local\Temp\2IuJTIpaYbDBuKO1iodGiiwxWXC\resources\app.asar\server\dist\app.js:2:226906)
    at C:\Users\sirynka\AppData\Local\Temp\2IuJTIpaYbDBuKO1iodGiiwxWXC\resources\app.asar\server\dist\app.js:2:115638
    at Array.forEach (<anonymous>)
    at f (C:\Users\sirynka\AppData\Local\Temp\2IuJTIpaYbDBuKO1iodGiiwxWXC\resources\app.asar\server\dist\app.js:2:115618)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

2025-09-18T14:13:34.113Z [info] Completed downloads cleared
2025-09-18T14:13:34.633Z [info] Completed downloads cleared
2025-09-18T14:13:59.133Z [info] Adding https://deezer.com/playlist/6742402844 to queue
2025-09-18T14:14:02.313Z [error] Cannot read properties of undefined (reading 'HREF')
TypeError: Cannot read properties of undefined (reading 'HREF')
    at map_track (C:\Users\sirynka\AppData\Local\Temp\2IuJTIpaYbDBuKO1iodGiiwxWXC\resources\app.asar\server\dist\app.js:2:226906)
    at C:\Users\sirynka\AppData\Local\Temp\2IuJTIpaYbDBuKO1iodGiiwxWXC\resources\app.asar\server\dist\app.js:2:115638
    at Array.forEach (<anonymous>)
    at f (C:\Users\sirynka\AppData\Local\Temp\2IuJTIpaYbDBuKO1iodGiiwxWXC\resources\app.asar\server\dist\app.js:2:115618)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Treychik** [comment]
<img width="544" height="63" alt="Image" src="https://github.com/user-attachments/assets/18c59a7b-6ac3-4467-8977-4a214ea4072a" />

same error. I have it deployed on my Synology NAS yesterday. 
Current WebUI Version: 1.9.3
Current Version: 2022.12.22-r222.5d447b6035
deemix lib version: 3.6.14

Any fix for it? album and other downloads work fine, but when trying to download liked songs in batch (and I have more than 5000 songs!) - it gives this error. is there a fix or a workaround?
