### ISSUE TITLE
Unable to download own personal playlists

### ISSUE THREAD

**Issue by Sunii** [bambanah/deemix#148]
**Describe the bug**
Logging in using my personal ARL and going to Favorites > Tracks, refreshing, and clicking "Download 0 Tracks" (there are over 1000 tracks in the playlist fyi) shows no error in the gui but gives the following error in the log:

`[info] Adding https://deezer.com/playlist/4586019448 to queue
Trace: PermissionException: PermissionException: playlist/4586019448 An active access token must be used to query information about the current user
    at API.call (file:///app/deezer-sdk/dist/index.js:276:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generatePlaylistItem (file:///app/deemix/dist/index.js:5060:21)
    at async DeemixApp.addToQueue (file:///app/webui/dist/deemixApp.js:150:37)
    at async handler (file:///app/webui/dist/routes/api/post/addToQueue.js:18:15)
    at generatePlaylistItem (file:///app/deemix/dist/index.js:5062:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DeemixApp.addToQueue (file:///app/webui/dist/deemixApp.js:150:37)
    at async handler (file:///app/webui/dist/routes/api/post/addToQueue.js:18:15)`

**Screenshots**
![librewolf_qKJ6svCXPe](https://github.com/user-attachments/assets/f7fce6b1-25cb-4c7f-91db-ed9e2d59fd35)

**Comment by DJBackalley** [comment]
Any Luck w/ this? me too! 
<img width="567" alt="image" src="https://github.com/user-attachments/assets/0be8ef07-3f99-441c-8370-08ac457fc97f">
<img width="1021" alt="image" src="https://github.com/user-attachments/assets/97f1340b-6923-48db-9660-cdc718b7add9">


but this 'title' error is messing with me! its been a min since i've used python so any help would be great
